### PR TITLE
Enable individual testing with Makefile.jst

### PR DESCRIPTION
**Pull request by goldfirere**

### CODE REVIEW

**Comment by antalsz** [comment]
This looks good, but why do we need this over and above `make -C testsuite`?  And `make -C testsuite` provides a few more targets; it would be good to have those too.  (We don't really use `LIST=`, but I use `test-$PREFIX` and even more so `parallel-$PREFIX` all the time.)  That said, I'd approve this as-is, it looks good to me.

**Review by antalsz — APPROVED** [review]

**Comment by goldfirere** [comment]
This works with the new dune-based build system. Without this change, you would have to build using the old build system in order to run any less than the entire testsuite. In conversation, @stedolan and I agreed that there were even further improvements beyond just this possible, but this was what I needed to move forward.

**Comment by goldfirere** [comment]
This seems to work and there appears to be little downside to merging. Still happy for review from @stedolan.

**Comment by stedolan** [comment]
Thanks! Looks good.

**Pull request merged**
