### PR TITLE
Resolve conflicts in Lambda, Printlambda, Simplif and Tmc

### PR DESCRIPTION
**Pull request by mshinwell**
Can't check the build yet due to conflicts in cmi files in `typing/`

### CODE REVIEW

**Review by ncik-roberts — APPROVED** [review]
Looks good to me, I think we can merge. And if we find out there are build issues later we can fix them later (either when I work on translation or when Chris fixes the problems with type-checking mlis).

**Comment by mshinwell** [comment]
This now has conflicts resolved in `Printlambda`, `Simplif` and `Tmc` too.
I'll start building this shortly using #175.

**Review by ncik-roberts — CHANGES_REQUESTED** [review]
This "request changes" just blocks my previous "approval" which was done before the current batch of changes.

I don't think I should necessarily be the reviewer for these changes. I do notice a few build errors now that it's rebased:

```
$ dune b --workspace=duneconf/boot.ws _build/default/.ocamlcommon.objs/native/lambda.cmx
File "lambda/lambda.ml", line 1419, characters 2-30:
Error: The constructor Pfield expects 3 argument(s),
       but is applied here to 2 argument(s)
$ dune b --workspace=duneconf/boot.ws _build/default/.ocamlcommon.objs/native/simplif.cmx
File "lambda/simplif.ml", line 937, characters 12-31:
Error: This expression has type Lambda.lfunction -> 'a -> 'b -> 'c
       but an expression was expected of type 'a
       The type variable 'a occurs inside Lambda.lfunction -> 'a -> 'b -> 'c
$ dune b --workspace=duneconf/boot.ws _build/default/.ocamlcommon.objs/native/printlambda.cmx
File "lambda/printlambda.ml", line 295, characters 4-19:
Error: The constructor Pfield expects 3 argument(s),
       but is applied here to 2 argument(s)               

```

**Comment by ncik-roberts** [comment]
I'm going to split out `lambda.mli` into another PR so we can merge that today.

**Comment by goldfirere** [comment]
Closing in favor of #185.

**Pull request closed without merging**
